logdir: ../../../logs/deep-svdd/mnist/debug
test_epoch: 30

train_data_params:
  labels:
    - 0
  target_size:
    - 32
    - 32

model_params:
    output_dim: 32
    nb_filter: 8
    normalization: 
    downsampling: stride

solver_params:
  lr: 0.001
  objective: one-class

fit_params:
  batch_size: 128
  nb_epoch: 30
  save_steps: 10
