logdir: ../../../logs/anogan/mnist/debug4
test_epoch: 100

train_data_params:
  labels:
    - 0

generator_params:
  latent_dim: 32
  nb_filter: 16
  last_activation: tanh
  normalization: batch
  upsampling: deconv

discriminator_params:
  nb_filter: 16
  normalization: batch
  downsampling: stride

solver_params:
  lr_g: 0.0001
  lr_d: 0.0001

fit_params:
  nb_epoch: 100
  visualize_steps: 1
  save_steps: 1
