logdir: ../../../logs/dagmm/mnist/debug
test_epoch: 100

train_data_params:
  labels:
    - 0
  target_size:
    - 32
    - 32

autoencoder_params:
  latent_dim: 2
  nb_filter: 16
  last_activation: tanh
  normalization: batch
  upsampling: deconv
  downsampling: stride

estimator_params:
  dense_units:
    - 32
    - 5
  normalization: batch

solver_params:
  lr: 0.001

fit_params:
  batch_size: 512
  nb_epoch: 100
  save_steps: 100
