logdir: ../../../logs/anogan/mnist/debug
test_epoch: 30

train_data_params:
  labels:
    - 0

generator_params:
  latent_dim: 128
  nb_filter: 64
  last_activation: tanh
  normalization: batch
  upsampling: deconv

discriminator_params:
  nb_filter: 64
  normalization: batch
  downsampling: stride

solver_params:
  lr_g: 0.001
  lr_d: 0.00001

fit_params:
  nb_epoch: 30
  visualize_steps: 1
  save_steps: 10

score_computer_params:
  lambda_: 0.1
  lr: 10.0

compute_params:
  batch_size: 128
  iteration: 50
